backend:
  name: github
  repo: lionelgabriel1/Novo-site_Eva
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

site_url: "https://tiporeisemservico.online"

collections:
  - name: "site_content"
    label: "Conteúdo do Site"
    files:
      - file: "src/content/siteContent.js"
        label: "Site Content"
        name: "site_content"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "text" }
              - { label: "Palavras-chave", name: "keywords", widget: "string" }
              - { label: "Robots", name: "robots", widget: "string" }
              - { label: "Canonical (URL)", name: "canonical", widget: "string" }

          - label: "Open Graph"
            name: "og"
            widget: "object"
            fields:
              - { label: "Título OG", name: "title", widget: "string" }
              - { label: "Descrição OG", name: "description", widget: "text" }
              - { label: "URL OG", name: "url", widget: "string" }
              - { label: "Imagem OG", name: "image", widget: "string" }

          - label: "Twitter"
            name: "twitter"
            widget: "object"
            fields:
              - { label: "Título Twitter", name: "title", widget: "string" }
              - { label: "Descrição Twitter", name: "description", widget: "string" }

          - label: "Schema"
            name: "schema"
            widget: "object"
            fields:
              - { label: "Nome", name: "name", widget: "string" }
              - { label: "Descrição", name: "description", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - label: "Imagem Hero"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Texto do Botão", name: "buttonText", widget: "string" }
              - { label: "Link do Botão", name: "buttonLink", widget: "string" }

          - label: "Vídeo Jogo"
            name: "game"
            widget: "object"
            fields:
              - { label: "ID do Vídeo (YouTube)", name: "videoId", widget: "string" }

          - label: "Prêmios"
            name: "prize"
            widget: "object"
            fields:
              - label: "Imagem Prêmio"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link Prêmio", name: "link", widget: "string" }

          - label: "Estrelas"
            name: "stars"
            widget: "object"
            fields:
              - label: "Imagem Estrelas"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link Estrelas", name: "link", widget: "string" }

          - label: "VIP"
            name: "vip"
            widget: "object"
            fields:
              - label: "Imagem VIP"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link VIP", name: "link", widget: "string" }

          - label: "Cadastro"
            name: "register"
            widget: "object"
            fields:
              - { label: "Título Cadastro", name: "title", widget: "string" }
              - label: "Imagem Cadastro"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link Cadastro", name: "link", widget: "string" }
              - { label: "Título Instruções", name: "instructionsTitle", widget: "string" }
              - name: "instructions", label: "Instruções", widget: "list", field: { name: "step", label: "Passo", widget: "string" }

          - label: "CTA"
            name: "cta"
            widget: "object"
            fields:
              - label: "Imagem CTA"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Botão CTA", name: "buttonText", widget: "string" }
              - { label: "Link CTA", name: "buttonLink", widget: "string" }
