backend:
  name: github
  repo: lionelgabriel1/Novo-site_Eva
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

locale: "pt"
site_url: "https://tiporeisemservico.online"

collections:
  - name: "conteudo"
    label: "Conteúdo do Site"
    files:
      - file: "src/content/siteContent.js"
        label: "Conteúdo Principal"
        name: "siteContent"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "text" }
              - { label: "Palavras-chave", name: "keywords", widget: "string" }
              - { label: "Robots", name: "robots", widget: "string" }
              - { label: "Canonical", name: "canonical", widget: "string" }

          - label: "Open Graph"
            name: "og"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "text" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Imagem", name: "image", widget: "string" }

          - label: "Twitter"
            name: "twitter"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Descrição", name: "description", widget: "text" }

          - label: "Link de Registro"
            name: "links"
            widget: "object"
            fields:
              - { label: "URL de Registro", name: "register", widget: "string" }

          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - label: "Imagem"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Texto do Botão", name: "buttonText", widget: "string" }
              - { label: "Link do Botão", name: "buttonLink", widget: "string" }

          - label: "Vídeo do Jogo"
            name: "game"
            widget: "object"
            fields:
              - { label: "YouTube Video ID", name: "videoId", widget: "string" }

          - label: "Imagem de Prêmio"
            name: "prize"
            widget: "object"
            fields:
              - label: "Imagem"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }

          - label: "Avaliações (Estrelas)"
            name: "stars"
            widget: "object"
            fields:
              - label: "Imagem"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }

          - label: "VIP"
            name: "vip"
            widget: "object"
            fields:
              - label: "Imagem"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }

          - label: "Cadastro"
            name: "register"
            widget: "object"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - label: "Imagem"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Título das Instruções", name: "instructionsTitle", widget: "string" }
              - label: "Passos"
                name: "instructions"
                widget: "list"
                field: { label: "Passo", name: "step", widget: "string" }

          - label: "Chamada para Ação (CTA)"
            name: "cta"
            widget: "object"
            fields:
              - label: "Imagem"
                name: "image"
                widget: "object"
                fields:
                  - { label: "URL", name: "src", widget: "string" }
                  - { label: "Alt", name: "alt", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Texto do Botão", name: "buttonText", widget: "string" }
              - { label: "Link do Botão", name: "buttonLink", widget: "string" }
